export default {
  isAuthenticated: state => !!state.token,
  authUser: state => state.authUser,
  errors: state => state.error,
  loadingUser: state => state.loading.user,
  loadingUI: state => state.loading.ui,
  loadingForm: state => state.loading.form,
  discoverProfiles: state => state.discoverProfiles,
  newestProfiles: state => state.newestProfiles,
  searchResults: state => state.searchResults,
  searchTotal: state => state.searchTotal,
  bookmarks: state => state.bookmarks,
  visitors: state => state.visitors,
  likesSent: state => state.likesSent,
  likesReceived: state => state.likesReceived,
  lastMatchResult: state => state.lastMatchResult,
  matches: state => state.matches,
  conversations: state => state.conversations,
  currentConversation: state => state.currentConversation,
  currentConversationMessages: state => state.currentConversationMessages,
  blockedUsers: state => state.blockedUsers,
  viewedProfile: state => state.viewedProfile
}
